name: Node.js CI

on:
  push:
    branches:
      - ghpages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ghpages
          persist-credentials: false

      - run: yarn install --ignore-scripts
      - run: npm run build
      - run: npm run export
      - run: node nojekyll.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: out
          silent: true