name: Build gh-pages CI
on:
  push:
    branches:
      - ghpages
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ghpages
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm install --ignore-scripts --legacy-peer-deps=true
      - run: yarn install --ignore-scripts
      - run: npm run build
      - run: npm run export
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: out
          silent: true